# Generated by Django 4.2.7 on 2025-03-19 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 8, 28, 4, 546866, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
